#!/usr/bin/env wish9
# Copyright © 2025 Mark Summerfield. All rights reserved.

if {![catch {file readlink [info script]} name]} {
    const APPPATH [file dirname $name]
} else {
    const APPPATH [file normalize [file dirname [info script]]]
}
tcl::tm::path add $APPPATH

const APPNAME CharFind
const VERSION 1.2.0
const UNIDATA_FILE [file join $APPPATH unidata.db]

package require config
Config new ;# we need tk scaling done early

package require app

[App new] show
